### ISSUE TITLE
Can I ask you some question?

### ISSUE THREAD

**Issue by denghannian** [hsabaghianb/KU_PN_Tool#1]
Dear friend,
  Thank you for your resource.Is it a tool box of matlab.And I do not know how to use it .Can you guide me to use it?
Thank you very much.
 
Deng Hannian

**Comment by hsabaghianb** [comment]
Thank you for your message. Run 'KUPNTool.m' which is in the folder 'KU_PN_Tool_Main_Function' 
In the GUI window select a PN model, a text file for simulation report and set the maximum simulation step (for example 100000).
Several PN model can be find in the 'example' folder.
Different type of PN model (immediate, timed, SPN, GSPN and different combinations of them) can be described similarly. 
In the GUI window you can click on the buttons to draw PN graph, draw reachability graph, draw Markov model, do the analytical solution (if any) and simulate the model.
The attached file is a paper that introduces this tool in Persian (Farsi).
[scj-v7n1p2-fa_2020.pdf](https://github.com/hsabaghianb/KU_PN_Tool/files/8106481/scj-v7n1p2-fa_2020.pdf)

**Comment by denghannian** [comment]
Thank you very much.Are you major in the petri-net? I am study it.I want to know that you how to learn it.I want to get the code of petri-net and optimization algorithm.
